### ISSUE TITLE
Ignore vertical scroll, but keep page scroll

### ISSUE THREAD

**Issue by mateuspv** [davideperozzi/momentum-js#5]
Hi, 
I have a huge horizontal timeline that exceeds the user's screen, the idea is use momentum to drag the timeline horizontally. Since I don't want to drag the timeline vertically, I've locked it: `lockAxis: {y: true}`

The problem is that locking the `Y` axis, the user is not able to scroll down the page. Do you have any hint about how to fix it ? Thanks

**Comment by davideperozzi** [comment]
Hey @mateuspv!

I think the problem here is, that the scroll event is being prevented from the stopPropagation function, which gets called after the user hit the element:

https://github.com/davideperozzi/momentum-js/blob/master/src/momentum/Handler.js#L593

I could add a option to disable the event propagation for specific events.
Before I can do that, I need to reproduce the issue. 

Maybe you have something like a **jsfiddle** for that already?
That would save me a little time.

And thank you for using momentum! :)

**Comment by mateuspv** [comment]
@davideperozzi Hi, sorry for the delay,
Here is  an example: https://jsfiddle.net/jh9ddsyf/73/ Please scroll down the page, you shall see the timeline. I believe that is `stopPropagation` too, a option for that would be great.

Since it is a problem only for mobile devices, I'm testing on Chrome mobile & safari(iPad 3), you can also reproduce on chrome dev tools mobile simulator.

Thanks for the support 👍

**Comment by davideperozzi** [comment]
@mateuspv Hey, sorry didn't had time to do anything the past days. 

Thanks for the jsfiddle, it's going to help me a lot! 
I will be able to publish something at the end of this week, hopefully :)

**Comment by davideperozzi** [comment]
@mateuspv Sorry, had much work last week, but finally got it to work. 

I updated your jsfiddle: https://jsfiddle.net/jh9ddsyf/76/

Now you can determine the threshold you want to reach before disabled the internal handlers, by adding this to your configuration: 

```js
preventMove: function(movedX, movedY, isTouchDevice) {
  return movedY > 5 && isTouchDevice;
} 
```

I tried a bit, but 5 seemed like the best value here.
Hope this is going to help you :)
