### ISSUE TITLE
Multiple objects dragged if overlapping 

### ISSUE THREAD

**Issue by peterssonanton** [davideperozzi/momentum-js#9]
Maybe I'm missing something, but I can't find a way to only drag the object on top if there are multiple close to or overlapping each other. When two elements are stacked on top of eachother they both get selected when dragging. JSfiddle here: https://jsfiddle.net/L4q65vu2/
Thanks :)

**Comment by davideperozzi** [comment]
Hey, there is not built-in functionality for this, since the handler is attached to the container which contains both elements. There is no checking in which layer the element is located in. It only checks the position. But you can implement this "z-index check" by yourself. Here's an example, which I've created quickly. Please do not use this in production. I only want to give you an idea on how this could be done: 

https://jsfiddle.net/davideperozzi/9h6203ms/

**Comment by peterssonanton** [comment]
Thanks for the help! I think this solution will be good enough for my case, do you want me to close the issue?

**Comment by davideperozzi** [comment]
You're welcome! Yeah, I'm going to close it. Feel free to open a new one if you need help! :)
